title: Navneet's Blog
description: > # this means to ignore newlines until "baseurl:"
  Find all the blogs by Navneet on Full-Stack Development (NodeJs, ReactJs, Containers, AWS and some DevOps tool).
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Navneet Lal Gupta # add your name
author-img: navneetlalg.jpg # add your photo
about-author: I am a full-stack developer focusing on nodejs and react. Always hungry to keep learning. # add description
social-twitter: lal_nlgupta
social-facebook: navneetlalg
social-github: navneetlal # add your Github handle
social-linkedin: navneetlalgupta
social-email: navneetlalg@gmail.com

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
